export type TokenStrategy = "exact" | "estimated";

export type ModelPricing = {
  providerId: string;
  providerLabel: string;
  modelId: string;
  modelLabel: string;
  tokenizerLabel: string;
  tokenizerEstimateDetail: string;
  tokenizerSourceLabel: string;
  tokenizerSourceUrl: string;
  tokenStrategy: TokenStrategy;
  inputCostPerMillionUsd: number;
  outputCostPerMillionUsd: number;
};

export const DEFAULT_PROMPT =
  "Summarize quarterly operations results for the executive team today.";

export const DEFAULT_OUTPUT =
  "Revenue rose 12 percent, backlog shrank, support replies accelerated, and retention stayed above target.";

const OPENAI_ESTIMATE_DETAIL =
  "Estimated with OpenAI's published rule of thumb: about 1 token per 4 characters and about 3/4 of a word.";

const OPENAI_TOKEN_GUIDE =
  "https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them";


const ANTHROPIC_ESTIMATE_DETAIL =
  "Estimated with the p50k_base approximation recommended for offline Claude estimation when countTokens is unavailable.";

const PROPEL_GUIDE =
  "https://www.propelcode.ai/blog/token-counting-tiktoken-anthropic-gemini-guide-2025";

const CLOUDFLARE_ESTIMATE_DETAIL =
  "Estimated with a generic rule of thumb of roughly 1 token per 4 characters for rough comparison only. Cloudflare pricing here uses token-denominated rates, not neuron pricing.";

const GEMINI_ESTIMATE_DETAIL =
  "Estimated using Google's SentencePiece-based tokenizer approximation. Gemini models use a custom tokenizer; offline estimates follow the ~4 characters per token rule of thumb. Pricing shown uses standard (non-batch) text/image/video rates for the ≤200k token context tier where tiered pricing applies.";

const GEMINI_PRICING_DOCS = "https://ai.google.dev/gemini-api/docs/pricing";

export const MODEL_PRICING: ModelPricing[] = [
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3.2-1b-instruct",
    modelLabel: "@cf/meta/llama-3.2-1b-instruct",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.027,
    outputCostPerMillionUsd: 0.201,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3.2-3b-instruct",
    modelLabel: "@cf/meta/llama-3.2-3b-instruct",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.051,
    outputCostPerMillionUsd: 0.335,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3.1-8b-instruct-fp8-fast",
    modelLabel: "@cf/meta/llama-3.1-8b-instruct-fp8-fast",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.045,
    outputCostPerMillionUsd: 0.384,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3.2-11b-vision-instruct",
    modelLabel: "@cf/meta/llama-3.2-11b-vision-instruct",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.049,
    outputCostPerMillionUsd: 0.676,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3.1-70b-instruct-fp8-fast",
    modelLabel: "@cf/meta/llama-3.1-70b-instruct-fp8-fast",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.293,
    outputCostPerMillionUsd: 2.253,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3.3-70b-instruct-fp8-fast",
    modelLabel: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.293,
    outputCostPerMillionUsd: 2.253,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-deepseek-r1-distill-qwen-32b",
    modelLabel: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
    tokenizerLabel: "Qwen-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.497,
    outputCostPerMillionUsd: 4.881,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-mistral-7b-instruct-v0-1",
    modelLabel: "@cf/mistral/mistral-7b-instruct-v0.1",
    tokenizerLabel: "Mistral-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.11,
    outputCostPerMillionUsd: 0.19,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-mistral-small-3.1-24b-instruct",
    modelLabel: "@cf/mistralai/mistral-small-3.1-24b-instruct",
    tokenizerLabel: "Mistral-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.351,
    outputCostPerMillionUsd: 0.555,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3.1-8b-instruct",
    modelLabel: "@cf/meta/llama-3.1-8b-instruct",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.282,
    outputCostPerMillionUsd: 0.827,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3.1-8b-instruct-fp8",
    modelLabel: "@cf/meta/llama-3.1-8b-instruct-fp8",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.152,
    outputCostPerMillionUsd: 0.287,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3.1-8b-instruct-awq",
    modelLabel: "@cf/meta/llama-3.1-8b-instruct-awq",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.123,
    outputCostPerMillionUsd: 0.266,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3-8b-instruct",
    modelLabel: "@cf/meta/llama-3-8b-instruct",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.282,
    outputCostPerMillionUsd: 0.827,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-3-8b-instruct-awq",
    modelLabel: "@cf/meta/llama-3-8b-instruct-awq",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.123,
    outputCostPerMillionUsd: 0.266,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-2-7b-chat-fp16",
    modelLabel: "@cf/meta/llama-2-7b-chat-fp16",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.556,
    outputCostPerMillionUsd: 6.667,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-guard-3-8b",
    modelLabel: "@cf/meta/llama-guard-3-8b",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.484,
    outputCostPerMillionUsd: 0.03,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-meta-llama-4-scout-17b-16e-instruct",
    modelLabel: "@cf/meta/llama-4-scout-17b-16e-instruct",
    tokenizerLabel: "Llama-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.27,
    outputCostPerMillionUsd: 0.85,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-google-gemma-3-12b-it",
    modelLabel: "@cf/google/gemma-3-12b-it",
    tokenizerLabel: "Gemma-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.345,
    outputCostPerMillionUsd: 0.556,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-qwen-qwq-32b",
    modelLabel: "@cf/qwen/qwq-32b",
    tokenizerLabel: "Qwen-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.66,
    outputCostPerMillionUsd: 1,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-qwen-qwen2.5-coder-32b-instruct",
    modelLabel: "@cf/qwen/qwen2.5-coder-32b-instruct",
    tokenizerLabel: "Qwen-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.66,
    outputCostPerMillionUsd: 1,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-qwen-qwen3-30b-a3b-fp8",
    modelLabel: "@cf/qwen/qwen3-30b-a3b-fp8",
    tokenizerLabel: "Qwen-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.051,
    outputCostPerMillionUsd: 0.335,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-openai-gpt-oss-120b",
    modelLabel: "@cf/openai/gpt-oss-120b",
    tokenizerLabel: "OpenAI-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.35,
    outputCostPerMillionUsd: 0.75,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-openai-gpt-oss-20b",
    modelLabel: "@cf/openai/gpt-oss-20b",
    tokenizerLabel: "OpenAI-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.2,
    outputCostPerMillionUsd: 0.3,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-aisingapore-gemma-sea-lion-v4-27b-it",
    modelLabel: "@cf/aisingapore/gemma-sea-lion-v4-27b-it",
    tokenizerLabel: "Gemma-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.351,
    outputCostPerMillionUsd: 0.555,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-ibm-granite-4.0-h-micro",
    modelLabel: "@cf/ibm-granite/granite-4.0-h-micro",
    tokenizerLabel: "Granite-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.017,
    outputCostPerMillionUsd: 0.112,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-zai-glm-4.7-flash",
    modelLabel: "@cf/zai-org/glm-4.7-flash",
    tokenizerLabel: "GLM-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.06,
    outputCostPerMillionUsd: 0.4,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-nvidia-nemotron-3-120b-a12b",
    modelLabel: "@cf/nvidia/nemotron-3-120b-a12b",
    tokenizerLabel: "Nemotron-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.5,
    outputCostPerMillionUsd: 1.5,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-moonshotai-kimi-k2.5",
    modelLabel: "@cf/moonshotai/kimi-k2.5",
    tokenizerLabel: "Kimi-family estimate",
    tokenizerEstimateDetail:
      "Estimated with a generic rule of thumb of roughly 1 token per 4 characters for rough comparison only. Cloudflare pricing here uses standard input and output token rates; cached input pricing is not currently shown in the table.",
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.6,
    outputCostPerMillionUsd: 3,
  },
  {
    providerId: "cloudflare",
    providerLabel: "Cloudflare Workers AI",
    modelId: "cloudflare-google-gemma-4-26b-a4b-it",
    modelLabel: "@cf/google/gemma-4-26b-a4b-it",
    tokenizerLabel: "Gemma-family estimate",
    tokenizerEstimateDetail: CLOUDFLARE_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.1,
    outputCostPerMillionUsd: 0.3,
  },
  {
    providerId: "google",
    providerLabel: "Google",
    modelId: "google-gemini-3.1-pro-preview",
    modelLabel: "Gemini 3.1 Pro Preview",
    tokenizerLabel: "Gemini estimate",
    tokenizerEstimateDetail: GEMINI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Gemini pricing docs",
    tokenizerSourceUrl: GEMINI_PRICING_DOCS,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 2.0,
    outputCostPerMillionUsd: 12.0,
  },
  {
    providerId: "google",
    providerLabel: "Google",
    modelId: "google-gemini-3-flash-preview",
    modelLabel: "Gemini 3 Flash Preview",
    tokenizerLabel: "Gemini estimate",
    tokenizerEstimateDetail: GEMINI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Gemini pricing docs",
    tokenizerSourceUrl: GEMINI_PRICING_DOCS,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.5,
    outputCostPerMillionUsd: 3.0,
  },
  {
    providerId: "google",
    providerLabel: "Google",
    modelId: "google-gemini-3.1-flash-lite-preview",
    modelLabel: "Gemini 3.1 Flash-Lite Preview",
    tokenizerLabel: "Gemini estimate",
    tokenizerEstimateDetail: GEMINI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Gemini pricing docs",
    tokenizerSourceUrl: GEMINI_PRICING_DOCS,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.25,
    outputCostPerMillionUsd: 1.5,
  },
  {
    providerId: "google",
    providerLabel: "Google",
    modelId: "google-gemini-2.5-pro",
    modelLabel: "Gemini 2.5 Pro",
    tokenizerLabel: "Gemini estimate",
    tokenizerEstimateDetail: GEMINI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Gemini pricing docs",
    tokenizerSourceUrl: GEMINI_PRICING_DOCS,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 1.25,
    outputCostPerMillionUsd: 10.0,
  },
  {
    providerId: "google",
    providerLabel: "Google",
    modelId: "google-gemini-2.5-flash",
    modelLabel: "Gemini 2.5 Flash",
    tokenizerLabel: "Gemini estimate",
    tokenizerEstimateDetail: GEMINI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Gemini pricing docs",
    tokenizerSourceUrl: GEMINI_PRICING_DOCS,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.3,
    outputCostPerMillionUsd: 2.5,
  },
  {
    providerId: "google",
    providerLabel: "Google",
    modelId: "google-gemini-2.5-flash-lite",
    modelLabel: "Gemini 2.5 Flash-Lite",
    tokenizerLabel: "Gemini estimate",
    tokenizerEstimateDetail: GEMINI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Gemini pricing docs",
    tokenizerSourceUrl: GEMINI_PRICING_DOCS,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.1,
    outputCostPerMillionUsd: 0.4,
  },
  {
    providerId: "google",
    providerLabel: "Google",
    modelId: "google-gemini-2.0-flash",
    modelLabel: "Gemini 2.0 Flash (deprecated)",
    tokenizerLabel: "Gemini estimate",
    tokenizerEstimateDetail: GEMINI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Gemini pricing docs",
    tokenizerSourceUrl: GEMINI_PRICING_DOCS,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.1,
    outputCostPerMillionUsd: 0.4,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5.4",
    modelLabel: "GPT-5.4",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 2.5,
    outputCostPerMillionUsd: 15.0,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5.4-mini",
    modelLabel: "GPT-5.4 Mini",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.75,
    outputCostPerMillionUsd: 4.5,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5.4-nano",
    modelLabel: "GPT-5.4 Nano",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.2,
    outputCostPerMillionUsd: 1.25,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5.2-pro",
    modelLabel: "GPT-5.2 Pro",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 21.0,
    outputCostPerMillionUsd: 168.0,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5.2",
    modelLabel: "GPT-5.2",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 1.75,
    outputCostPerMillionUsd: 14.0,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5.1",
    modelLabel: "GPT-5.1",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 1.25,
    outputCostPerMillionUsd: 10.0,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5-pro",
    modelLabel: "GPT-5 Pro",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 15.0,
    outputCostPerMillionUsd: 120.0,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5",
    modelLabel: "GPT-5",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 1.25,
    outputCostPerMillionUsd: 10.0,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5-mini",
    modelLabel: "GPT-5 Mini",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.25,
    outputCostPerMillionUsd: 2.0,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-5-nano",
    modelLabel: "GPT-5 Nano",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.05,
    outputCostPerMillionUsd: 0.4,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-4.1",
    modelLabel: "GPT-4.1",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 2.0,
    outputCostPerMillionUsd: 8.0,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-4o",
    modelLabel: "GPT-4o",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 2.5,
    outputCostPerMillionUsd: 10.0,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-4o-mini",
    modelLabel: "GPT-4o Mini",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.15,
    outputCostPerMillionUsd: 0.6,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-o4-mini",
    modelLabel: "o4-mini",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 1.1,
    outputCostPerMillionUsd: 4.4,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-4.1-nano",
    modelLabel: "GPT-4.1 Nano",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.1,
    outputCostPerMillionUsd: 0.4,
  },
  {
    providerId: "openai",
    providerLabel: "OpenAI",
    modelId: "openai-gpt-4.1-mini",
    modelLabel: "GPT-4.1 Mini",
    tokenizerLabel: "OpenAI estimate",
    tokenizerEstimateDetail: OPENAI_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "OpenAI token guide",
    tokenizerSourceUrl: OPENAI_TOKEN_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.4,
    outputCostPerMillionUsd: 1.6,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-opus-4-6",
    modelLabel: "Claude Opus 4.6",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 5,
    outputCostPerMillionUsd: 25,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-opus-4-5",
    modelLabel: "Claude Opus 4.5",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 5,
    outputCostPerMillionUsd: 25,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-opus-4-1",
    modelLabel: "Claude Opus 4.1",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 15,
    outputCostPerMillionUsd: 75,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-opus-4",
    modelLabel: "Claude Opus 4",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 15,
    outputCostPerMillionUsd: 75,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-sonnet-4-6",
    modelLabel: "Claude Sonnet 4.6",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 3,
    outputCostPerMillionUsd: 15,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-sonnet-4-5",
    modelLabel: "Claude Sonnet 4.5",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 3,
    outputCostPerMillionUsd: 15,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-sonnet-4",
    modelLabel: "Claude Sonnet 4",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 3,
    outputCostPerMillionUsd: 15,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-sonnet-3-7",
    modelLabel: "Claude Sonnet 3.7 (deprecated)",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 3,
    outputCostPerMillionUsd: 15,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-haiku-4-5",
    modelLabel: "Claude Haiku 4.5",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 1,
    outputCostPerMillionUsd: 5,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-haiku-3-5",
    modelLabel: "Claude Haiku 3.5",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.8,
    outputCostPerMillionUsd: 4,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-opus-3",
    modelLabel: "Claude Opus 3 (deprecated)",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 15,
    outputCostPerMillionUsd: 75,
  },
  {
    providerId: "anthropic",
    providerLabel: "Anthropic",
    modelId: "anthropic-claude-haiku-3",
    modelLabel: "Claude Haiku 3",
    tokenizerLabel: "Anthropic estimate",
    tokenizerEstimateDetail: ANTHROPIC_ESTIMATE_DETAIL,
    tokenizerSourceLabel: "Propel guide",
    tokenizerSourceUrl: PROPEL_GUIDE,
    tokenStrategy: "estimated",
    inputCostPerMillionUsd: 0.25,
    outputCostPerMillionUsd: 1.25,
  },
];
